### ISSUE TITLE
Relicense under dual MIT/Apache

### ISSUE THREAD

**Issue by cmr** [Nemo157/roaring-rs#14]
This would make this library suitable for including in the Rust standard distribution. (Note that Rust is primarily Apache licensed - it uses the MIT only for GPLv2 compatability)

**Comment by Nemo157** [comment]
Sounds good to me. @llogiq, @rayglover agreed?

**Comment by llogiq** [comment]
Agreed.

**Comment by rayglover** [comment]
:+1:
