### ISSUE TITLE
is_empty() returns false even when len() == 0

### ISSUE THREAD

**Issue by aeickhoff** [Nemo157/roaring-rs#18]
`is_empty()` just seems to check if there are any containers, which might be the case even if there are no items in them (after some operations, I don't understand the internals well enough yet to say why)

```rust
let mut test = RoaringBitmap::new();
test.insert(42u32);
let mut test2 = RoaringBitmap::new();
test2.insert(13u32);
let test3 = test & test2;
assert!(test3.len() == 0);
assert!(test3.is_empty()); // fails
```

**Comment by lemire** [comment]
I also do not know the internals of this implementation, but in other Roaring implementations, it is assumed that we do not store empty containers, even after doing some operations (such as an intersection).

**Comment by aeickhoff** [comment]
Thanks for your perspective, yes, this was my assumption based on how `is_empty()` is written.

**Comment by aeickhoff** [comment]
Apparently there is an appropriate container removal check for `difference_with`: https://github.com/Nemo157/roaring-rs/blob/a5683ab/src/imp.rs#L184 but not in `intersection_with` https://github.com/Nemo157/roaring-rs/blob/a5683ab/src/imp.rs#L169

I'm a bit short on time right now, might do a PR in the future!

**Comment by Nemo157** [comment]
Thanks for noticing this :smile:.

> it is assumed that we do not store empty containers

Yep, that matches my (vague) recollection about how this code should be behaving as well.

I think I should have time this evening to fix it, assuming the change is that simple. If it's easy enough I might also try and add some sort of `debug_assert` checking that the bitmap is fully consistent after the major operations to catch any other latent issues like this.

**Comment by Nemo157** [comment]
Turns out it's not just `is_empty` that assumes empty containers don't exist, `eq` also fails after a container is emptied by `intersection_with` 😢

```rust
use std::iter::FromIterator;
let test = RoaringBitmap::from_iter(&[42u32]);
let test2 = RoaringBitmap::from_iter(&[13u32]);
assert_eq!(test & test2, RoaringBitmap::new());
```

gives

```
assertion failed: `(left == right)` (left: `"RoaringBitmap<[]>"`, right: `"RoaringBitmap<[]>"`)
```

**Comment by aeickhoff** [comment]
Cool, thank you! Do you think you could publish a new release to cargo? Then I could get rid of some workarounds which I created for this bug.

**Comment by Nemo157** [comment]
Sure, might take a little while as I think I had to revoke my crates.io token since last time I published this, but I'll get it up ASAP.

**Comment by Nemo157** [comment]
Version 0.4.2 is published 🎉
